version: "3"
services:
  nginx:
      build:
        context: .
        dockerfile: nginxDockerfile
      # volumes:
      #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      #   - ./static:/usr/share/nginx/html/static
      ports:
        - "80:80"
      depends_on:
        - web
      networks:
        - frontend
  web:
    build: .
    ports:
      - "5000"
    depends_on:
      - mongodb
    networks:
        - backend
        - frontend
    
  mongodb:
    #image: mongo:5.0
    #image: mongo:3.0.2
    image: mongo:4.4
    #image: mongo
    ports:
      - "27017:27017"
    networks:
        - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      # MONGODB_ROOT_PASSWORD: root

networks:
  backend:
  frontend:
# volumes:
#   mongodb22:
